# Generated by Django 6.0.5 on 2026-05-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueling',
            name='fuel',
            field=models.CharField(choices=[('N', 'Nuclear'), ('P', 'Propellant'), ('G', 'GN particles')], max_length=1),
        ),
    ]